### ISSUE TITLE
How to use Supervisor?

### ISSUE THREAD

**Issue by stephanvierkant** [schmittjoh/JMSJobQueueBundle#104]
http://jmsyst.com/bundles/JMSJobQueueBundle/master/installation:
"For this bundle to work, you have to make sure that one (and only one) instance of the console command jms-job-queue:run is running at all times."

https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Resources/doc/installation.rst:
"For this bundle to work, make sure that you run at least one instance of the console command jms-job-queue:run (you can run as many as needed to process your events or guarantee high availability)."

Which one is true? :)

**Comment by jsafoodpanda** [comment]
Would also like to know. Wonder if this changed between versions.

**Comment by byhoratiss** [comment]
I've being able to install the program in supervisor following the documentation from the jmsyst.com.
The example was a good starting point.
Of course in production is better having supervisor handing the spawning & managing of processes.
The quantity of workers handling each Job can be configured.
Are you having problems?

Sorry for my english.

**Comment by maximium** [comment]
It looks like support for multiple workers added here https://github.com/schmittjoh/JMSJobQueueBundle/commit/922d005116cffc6609418281c29d46d6a2e03dbb 
so u need to check your version to find out which one is true for you
