### ISSUE TITLE
Enhacement: Requeue

### ISSUE THREAD

**Issue by ecentinela** [schmittjoh/JMSJobQueueBundle#11]
After a job fails (even retries), it will be useful to requeue the job from the control panel.
For example, the admin can see the application error, fix it, and requeue the job.
Maybe is as easy as updating some fields on jms_jobs when clicking on some button on the UI.
What do you think=

**Comment by joshribakoff** [comment]
Is there any way to automatically retry a job? For example if my worker interacts with an external API, and it causes a failure, it should have a counter incremented & be retried automatically until it succeeds or the counter reaches the maxRetries limit.
