### ISSUE TITLE
Twig functions deprecated 

### ISSUE THREAD

**Issue by stephanvierkant** [schmittjoh/JMSJobQueueBundle#112]
> The Twig_Filter_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.

https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Twig/JobQueueExtension.php#L31

> The Twig_Test_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleTest instead.

https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Twig/JobQueueExtension.php#L17

**Comment by Disparity** [comment]
:thumbsup:
