### ISSUE TITLE
Load file from Google

### ISSUE THREAD

**Issue by ickbinhier** [schmittjoh/JMSJobQueueBundle#130]
In this File on line 163 is a js file load from google
https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Resources/views/Job/details.html.twig#L163

Can not be the file locally? My server does not allow external load.

**Comment by stephanvierkant** [comment]
No, you can't.

http://stackoverflow.com/questions/9318620/include-jsapi-google-on-local-machine-not-from-google-com

**Comment by schmittjoh** [comment]
Closing this one here.
