### ISSUE TITLE
Compatibility with HHVM

### ISSUE THREAD

**Issue by bigfoot90** [schmittjoh/JMSJobQueueBundle#131]
In HHVM the `register_tick_function` is not implemented, and it ands in error when you call any command from `app/console`
https://3v4l.org/ijOlU#vhhvm-301
https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Console/Application.php#L36

**Comment by schmittjoh** [comment]
In that case, statistics might need to be disabled if you plan on running on the HHVM. I'll close this one here, if you have an alternative solution, please feel free to submit a PR.
