### ISSUE TITLE
add symfony 3 support

### ISSUE THREAD

**Issue by iveretelnyk** [schmittjoh/JMSJobQueueBundle#132]
Currently bundle required symfony/framework-bundle >=2.1,<3.0-dev

Please add support for symfony 3.

**Comment by ianfp** [comment]
There's more to it than just changing `composer.json`. For example, `RunCommand` assumes that the console is in the kernel root dir (`app`), but it's in `bin` in Symfony 3:

```php
// In RunCommand.php

    private function getCommandProcessBuilder()
    {
        // lines skipped...
        $pb
            ->add('php')
            ->add($this->getContainer()->getParameter('kernel.root_dir').'/console')
            ->add('--env='.$this->env)
        ;
        // Lines skipped...
    }

**Comment by stephanvierkant** [comment]
See Pull Request #122

**Comment by temp** [comment]
Can't this issue be closed?

**Comment by schmittjoh** [comment]
Yes, it can :)
