### ISSUE TITLE
Get command output in Job dependency

### ISSUE THREAD

**Issue by anacona16** [schmittjoh/JMSJobQueueBundle#137]
Hi, I have a Job with a dependency, but I need pass the output command of the dependent Job at main Job, the main Job need it.

```php
$job = new Job('a');
$dependentJob = new Job('b');
$dependentJob->addDependency($job);
$em->persist($job);
$em->persist($dependentJob);
$em->flush();
```

This is posible?

**Comment by schmittjoh** [comment]
It might be simpler to schedule the second job from within the first one.
