### ISSUE TITLE
Jobs not starting

### ISSUE THREAD

**Issue by bigfoot90** [schmittjoh/JMSJobQueueBundle#138]
why my jobs do not start? Am I missing something?
Symfony version: 2.7.6

Controller:
```php
            $job = new Job('my:sf:command', [], true, 'queue1');
            $this->em->persist($job);
            $this->em->flush($job);
```

Command:
```bash
$ app/console jms-job-queue:run --verbose
Cleaning up stale jobs
Running jobs
Signal Handlers have been installed.
```

```
$ cat app/logs/dev.log
[2016-05-17 17:00:51] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". [] []
```

thanks you in advance

**Comment by stephanvierkant** [comment]
Did you check if the Job is persisted? What does the database record look like?

**Comment by bigfoot90** [comment]
Yes, it has been persisted, but I don't have the database now since I was needing a fast working solution. Sorry.
I leave this open for other users, and for a deeper check in the future.

**Comment by Monpoke** [comment]
I had the same issue. To resolve it, I had to set the _date.timezone_ in the PHP configuration file, for the CLI. Now it works for me!

**Comment by bigfoot90** [comment]
@Monpoke +1 Thanks.

**Comment by kkarkus** [comment]
@bigfoot90 close issue please
