### ISSUE TITLE
Uncaught exception FatalThrowableError

### ISSUE THREAD

**Issue by dextervip** [schmittjoh/JMSJobQueueBundle#139]
I am running JMS Queue Bundle on dev-master with PHP 7 and Symfony 2.8. However I noticed some jobs are marked as "Finished" instead of failed when a FatalThrowableError exception is thrown.

State   Finished
Error Output

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function getDocumentoNumero() on boolean

**Comment by schmittjoh** [comment]
This seems to be an issue in your code.
