### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nenadalm** [schmittjoh/JMSJobQueueBundle#146]
Hi. It seems that jobs are not detached (at least not in my case) if they finish successfully. The problem seems to be this condition: https://github.com/schmittjoh/JMSJobQueueBundle/blob/61d30100ee490591feaa2adcba9052b78e7acea8/Entity/Repository/JobRepository.php#L269

maybe it should be changed to:

``` php
if ($job->isClosedNonSuccessful() && $job->isRetryJob()) {
    continue;
}
```

?

**Comment by schmittjoh** [comment]
I cannot say for sure, but from the comment on the line above this was intentionally done here. Did you run into errors? How long do you run the RunCommand itself?

Closing now, please just re-open if you have further feedback on this.
