### ISSUE TITLE
Job output from log file path

### ISSUE THREAD

**Issue by 0xPr0xy** [schmittjoh/JMSJobQueueBundle#150]
I think there's a use case for also implement a way to use a log file as job output.
Since not all commands output to stdOut, for example commands that run in a cron.

It would be quite simple to implement, you just set the log directory at the same time you are instantiating new jobs and persisting them.
Then in runCommand, if the output is empty when the command is done, just read the log contents instead.

**Comment by schmittjoh** [comment]
I would recommend to not use cron, but instead ``jms-job-queue:schedule`` which should be able to handle  those needs and you get excellent logging whether those commands ran as expected:
http://jmsyst.com/bundles/JMSJobQueueBundle/master/scheduled_jobs
