### ISSUE TITLE
Configure path to php cli

### ISSUE THREAD

**Issue by TheCelavi** [schmittjoh/JMSJobQueueBundle#154]
On shared environments and/or for some other reasons, it may be required to set explicitly path to PHP binaries for commands.

Currently, all jobs from queue are executed as:

php bin/console ... etc...

while in some cases there can be requirement to use:

/path/to/php/binary/php bin/console ... etc...

**Comment by tarnawski** [comment]
+1

**Comment by psylosss** [comment]
+1

**Comment by schmittjoh** [comment]
This has been fixed in the most recent version.
