### ISSUE TITLE
Log timestamps

### ISSUE THREAD

**Issue by iveretelnyk** [schmittjoh/JMSJobQueueBundle#156]
It might be already possible but I can find. 

When using with supervisor it logs exceptions and other stuff, but there is no ability to know when it happened as it just logs output from child proccess. 

Is it possible to have logs with timestamps? 

It probably not a bug. Thank you for your help!

**Comment by schmittjoh** [comment]
Not sure what you would like to see here, you already have the Job entity which contains timestamps and possible exception data?
