### ISSUE TITLE
repository queries do not return correct results

### ISSUE THREAD

**Issue by andrzejdziekonski** [schmittjoh/JMSJobQueueBundle#157]
Hi,

i have very odd issue. When using repository methods to fetch jobs (even simple findAll()) i receive 1 record but in my database there are much more. I firstly thought there is some paginator bug but even for $em->getRepository('JMSJobQueueBundle:Job')->findAll() i retrieve 1 record (with first job). 

Are there any filters, or repository methods that overwrite query results? I use 1.4 version of the bundle with MsSQL database.

**Comment by schmittjoh** [comment]
No, there is nothing in this bundle at least which intercepts queries.
