### ISSUE TITLE
Error from ScheduleCommand when running jms-job-queue:run

### ISSUE THREAD

**Issue by shannera** [schmittjoh/JMSJobQueueBundle#159]
I have version 1.4.0 installed, running on a server with PHP 7.0.14, but the problem also arises with PHP 5.6. When I run:
`/opt/plesk/php/7.0/bin/php app/console jms-job-queue:run --verbose ()`
I always get the following error. When I call the queued command manually everything works fine.
`Started Job(id = 21, command = "netzwunder:singlesite:generator").
Job 21: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /httpdocs/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Command/ScheduleCommand.php on line 54`
What is really weird is that ScheduleCommand.php seems to be called even when I execute the run command. The line mentioned in the error is the following:
`$jobsLastRunAt = $this->populateJobsLastRunAt($registry->getManagerForClass(CronJob::class), $jobSchedulers);`
and the problem seems to be with `$registry->getManagerForClass(CronJob::class)`. Anything I can do? The problem also exists with dev-master.

**Comment by shannera** [comment]
After browsing the other issues, this error would be fixed with the fix in https://github.com/schmittjoh/JMSJobQueueBundle/issues/155

**Comment by schmittjoh** [comment]
Should be fixed by https://github.com/schmittjoh/JMSJobQueueBundle/commit/cde4aec981b7b411737f466a0c86892cf3d8e717
