### ISSUE TITLE
Is this repository alive?

### ISSUE THREAD

**Issue by Aerendir** [schmittjoh/JMSJobQueueBundle#161]
I'd like to use it, but I see it has a lot of not merged pull requests and a lot of issues not solved.

So I'm asking: can I safely use this bundle?

I've seen it were updated to Symfony 3, but I'd like to better understand the current status of the bundle.

Thank you!

**Comment by schmittjoh** [comment]
It's stable and works quite well. Whether this is suitable depends on your concrete use-case though.

**Comment by Aerendir** [comment]
Ok, thankyou! I think it will be very good as it is really flexible as what I've seen!
