### ISSUE TITLE
Symfony 3.3: sh: 1: exec: exec: not found

### ISSUE THREAD

**Issue by stephanvierkant** [schmittjoh/JMSJobQueueBundle#171]
My job finished with exit code 127. Error output is `sh: 1: exec: exec: not found`

Using Symfony 3.3.0-RC1 on Ubuntu.

Maybe related to #8?

**Comment by stephanvierkant** [comment]
Commenting out [this line](https://github.com/schmittjoh/JMSJobQueueBundle/blob/1.4.1/Command/RunCommand.php#L432) fixes the problem for me, but I don't know what that means for other setups.

**Comment by schmittjoh** [comment]
Indeed, however this only fixes it for 3.3, but at the same time breaks for earlier versions. 

Following the discussion on Symfony, it seems like this is a BC break as @stof mentioned, but a quick fix on the bundle would be to build string command line and then use the Process class directly instead of going through the ProcessBuilder. 

Happy to merge something if you can provide a pull-request.

**Comment by anboo** [comment]
@schmittjoh Will this package work for Symfony 3.3? 
Or the support has stopped and we will wait for the pull request?

**Comment by schmittjoh** [comment]
@anboo, I think you do not understand how open-source works. If you need this right now, the steps for how to achieve it are above and a pull-request is certainly welcome. I'll also have a look at some point, but only when I need this change.

**Comment by anacona16** [comment]
@schmittjoh 

Do you thing a version comparison is enough to solve this?

Some thing like this:
```
if (Kernel::VERSION < '3.3.0') {
    $pb->add('exec');
}
```

If you agree with this, I can make a pull request.

**Comment by anacona16** [comment]
@schmittjoh please see PR #175

**Comment by Trekels** [comment]
Any updates on the PR #175 ?

**Comment by apsylone** [comment]
I think the PR #176 is better than #175.
It should be merged as it has been tested.
The Bundle is completely unusable in SF 3.3 without this fix merged.

**Comment by anorgan** [comment]
Until this gets merged, you can use

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:anorgan/JMSJobQueueBundle.git"
        }
    ]
}
```

in your `composer.json` to alias the repository and import the patched dependency
