### ISSUE TITLE
doctrine/dbal v2.7.0 doctrine:schema:update issue

### ISSUE THREAD

**Issue by gam6itko** [schmittjoh/JMSJobQueueBundle#204]
After updating doctrine/dbal to version `2.7.0` execution of `doctrine:schema:update` failed with errors below

```
  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE jms_job_related_entities ADD CONSTRAINT FK_E956F4E2BE04EA9 FOREIGN KEY (job_id) REFERENCES  jms_jobs (id)':

  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

  [PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```

Downgrade to v2.6.3 solves this problem.

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.21 - MySQL Community Server (GPL)
Protocol version: 10

**Comment by Ydalb** [comment]
Same problem here. Thanks for the tip.

**Comment by stephanvierkant** [comment]
See #206.

**Comment by dkorsak** [comment]
+1

**Comment by stephanvierkant** [comment]
@dkorsak Don't place a comment like '+1' but use reactions instead, preferably on the referenced PR.
