### ISSUE TITLE
Symfony 4: Error : Call to a member function getManagerForClass() on null

### ISSUE THREAD

**Issue by modstore** [schmittjoh/JMSJobQueueBundle#212]
I'm currently upgrading my symfony 3.3 project to 4. I'm getting this error with the following code:

`$existingJob = $this->em->getRepository(Job::class)->findJobForRelatedEntity(
                'app:my-command',
                $product,
                [Job::STATE_PENDING, Job::STATE_RUNNING]
            );`

I thought maybe I need the di-extra-bundle, but there doesn't seem to be a compatible version.

**Comment by schmittjoh** [comment]
fixed by the latest version
