### ISSUE TITLE
PHP  7.1.17 shouldSchedule Declaration  error

### ISSUE THREAD

**Issue by dkorsak** [schmittjoh/JMSJobQueueBundle#217]
Compile Error: Declaration of JMS\JobQueueBundle\Cron\CommandScheduler::shouldSchedule($_, DateTime $lastRunAt): bool must be compatible with JMS\JobQ  
  ueueBundle\Cron\JobScheduler::shouldSchedule(string $command, DateTime $lastRunAt): bool  

after execute command: jms-job-queue:schedule

**Comment by schmittjoh** [comment]
fixed in the latest version
