### ISSUE TITLE
Incorrect documentation regarding scheduling cron job with a CronCommand

### ISSUE THREAD

**Issue by mtuck063** [schmittjoh/JMSJobQueueBundle#227]
With regards to `scheduled_jobs.rst`, the documentation suggest that you must implement `JMS\JobQueueBundle\Command\CronCommand` when in fact it is `JMS\JobQueueBundle\Console\CronCommand` and secondly when implementing the `CronCommand` you must also tag the concrete class with `jms_job_queue.cron_command`, however this is not stated in the documentation.

**Comment by karlzakhary** [comment]
>  and secondly when implementing the `CronCommand` you must also tag the concrete class with `jms_job_queue.cron_command` 
Man, you're amazing!

**Comment by karlzakhary** [comment]
@schmittjoh  I think that should be updated since I have really stumbled for a while because of that missing procedure

**Comment by schmittjoh** [comment]
Is there a pull-request for the docs already?

**Comment by karlzakhary** [comment]
> Is there a pull-request for the docs already?

Yes, https://github.com/schmittjoh/JMSJobQueueBundle/pull/235

**Comment by schmittjoh** [comment]
Thanks, closing this here :+1:
