### ISSUE TITLE
Symfony parameters in Supervisor config file ?

### ISSUE THREAD

**Issue by Claymm** [schmittjoh/JMSJobQueueBundle#51]
How did you manage to send %kernel.root_dir% to your /etc/supervisord.config file ?

Is it possible to make some parameters dynamic regarding a Symfony project path in the Supervisor config file ?

**Comment by ggirtsou** [comment]
This was probably possible by using capistrano

**Comment by schmittjoh** [comment]
You need to make this part of your deployment procedure.
