### ISSUE TITLE
Load Balancing? Thoughts?

### ISSUE THREAD

**Issue by bassrock** [schmittjoh/JMSJobQueueBundle#67]
Hi,

I am curious if anyone has any thoughts on how we could make this bundle work on multiple servers. Here are a few of my thoughts (not neatly organized):

* Have the server when starting the runner command connect to the database and save information about itself. (capabilities, server information, allowed queues?, maybe allow this configurable on the web ui?)
* Add a server id/unique name to the job

Any thoughts for this?

**Comment by nclavaud** [comment]
Referencing #76 and #88 which are somehow related.

**Comment by estahn** [comment]
There should be some sort of leader election. When you have the nodes in the database flag one of them as leader. The non-leader nodes need to check for availability and eventually re-elect a new leader if the leader is unresponsive.

**Comment by schmittjoh** [comment]
Closing this here as this has been added a while ago. The bundle uses implicit row locking as supported by MySQL InnoDB and others.
