### ISSUE TITLE
Horizontal scaling job concurrency issue

### ISSUE THREAD

**Issue by jaredm4** [schmittjoh/JMSJobQueueBundle#76]
We wanted to test for the possibility that there's too many jobs for a single instance to handle, and add more instances to tackle more jobs. From initial tests, this is what looks like is happening:

* Both instance's job runners start and grab the same "pending" job row.
* Both set the state to "running", and continue to both run the job.

This is bad for obvious reasons but we also have our jobs create new jobs as needed after they complete. So this compounds the issue by adding new duplicate jobs at the end.

Can Innodb row-locking solve this issue? Has anyone else solved it? Scaling vertically is an option but only for so long. I foresee too many jobs for a single instance.

**Comment by ggirtsou** [comment]
@JeffreyDD can you provide a public blackfire.io profile so we can check the bottleneck (if any)?

**Comment by schmittjoh** [comment]
Closing as support for running multiple instances of ``jms-job-queue:run`` has been added a while ago.
