### ISSUE TITLE
Container doesn't get registered in the prod environment

### ISSUE THREAD

**Issue by florinutz** [schmittjoh/JMSJobQueueBundle#79]
`jms-job-queue:run --verbose --env=prod`

The run command always throws this error in the prod env, while it works fine in dev.

PHP Fatal error:  Uncaught exception 
'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'The parameter "jms_job_queue.statistics" must be defined.' in 
/home/florin/PhpstormProjects/dubios/app/cache/prod/appProdProjectContainer.php:1149

```
        $kernel->boot();
        if ($kernel->getContainer()->getParameter('jms_job_queue.statistics')) {
            $this->insertStatStmt = "INSERT INTO jms_job_statistics (job_id, characteristic, createdAt, charValue) VALUES (:jobId, :name, :createdAt, :value)";
            register_tick_function(array($this, 'onTick'));
        }
```

the bundle parameters are never registered in the prod container, any idea why?

**Comment by pkarecki** [comment]
thanks 👍
