### ISSUE TITLE
Can't use the console when no database available

### ISSUE THREAD

**Issue by fantoine** [schmittjoh/JMSJobQueueBundle#81]
I would like to validate my project through SensioLabsInsight but I get issues with this bundle because of the missing of databases on SensioLabsInsight VMs.

The main issue is due to composer scripts (clearCache,...) which call app/console, which load JMSJobQueueBundle, which get doctrine connections on boot, and then try to launch mysql connections.

I already fixed some issues on app/console calls by disabling statistics, but the part on the bundle file is not configurable...

I don't know if I can solve this with some workaround or if the bundle must be updated?

**Comment by ggirtsou** [comment]
Maybe you could try disabling the bundle in test environment, but that would raise issues when PHPUnit tries to mock Job entity.

In case this works for you there are two things you need to do:

Modify your app/console:
```php
use JMS\JobQueueBundle\Console\Application as JMSApplication;
use Symfony\Bundle\FrameworkBundle\Console\Application as SymfonyApplication;
// ....

$kernel = new AppKernel($env, $debug);
if ($env == 'test') {
    // load standard Application class
    $application = new SymfonyApplication($kernel);
} else {
    // load JMS Application
    $application = new JMSApplication($kernel);
}
// ....
```

You'd also need to modify your AppKernel.php to load the bundle only if current environment is not *test*:

```php
// AppKernel.php

// ....
        if ($this->getEnvironment() !== 'test') {
            $bundles[] = new JMS\JobQueueBundle\JMSJobQueueBundle();
            $bundles[] = new JMS\DiExtraBundle\JMSDiExtraBundle($this);
            $bundles[] = new JMS\AopBundle\JMSAopBundle()
        }
// ....
```

That won't work if you have JMSJobQueueBundle configuration defined in your .yml files.

Please notice this is not the solution, just a suggestion that might not work.

**Comment by fantoine** [comment]
I solved the issue by using a custom console script for SensioLabsInsights which doesn't extend JMSJob Application.

I also removed references to JMSJobBundle on AppKernel and from configuration files by using SensioLabsInsights pre_composer scripts.

Your fix could be a solution but since it's not on the main branch it's not a solution to use it..

Thx anyway
