### ISSUE TITLE
Graceful restart on code deployment?

### ISSUE THREAD

**Issue by nclavaud** [schmittjoh/JMSJobQueueBundle#83]
We have been using this bundle in production for a few days. However, last time we have deployed new code (containing a new job and console command) the job runner failed processing new jobs:
```
You have requested a non-existent service ...
```

Stopping and restarting the job runner solved the problem, so I guess this issue is related to our deployment process. We are using capistrano/capifony.

What is the proper way to achieve a graceful restart and make sure that the jobs published after deployment are processed by a fresh job runner? Are we supposed to let the runner stop on its own after maximum runtime has been reached, and let the auto-start mechanism (supervisord) handle the restart?

I am thinking of adding a special `shutdown` job in the queue (just before the new code is deployed) that will force the job runner to stop (and let it restart automatically), but maybe I have missed something.

**Comment by schmittjoh** [comment]
Yes, letting it exit itself, is the cleanest way to migrate to a new version.

I've been thinking about adding a signal handler which triggers the shutdown logic. If you need this, a pull-request would be appreciated.

**Comment by nclavaud** [comment]
Alright then. We have chosen the easy way:
  * disable the job runner auto-restart
  * wait for the current job runner to terminate
  * deploy new code
  * enable the job runner auto-restart

The only thing we need to care about is backward compatibility (make sure the new code is able to process old jobs), which is no major problem in our case.
