### ISSUE TITLE
How to gracefully terminate job runner?

### ISSUE THREAD

**Issue by ggirtsou** [schmittjoh/JMSJobQueueBundle#90]
When deploying application in AWS ElasticBeanstalk new app is extracted in `/var/app/current/` directory and running jobs change state to `Incomplete`.

That's because AWS quickly switches directories causing script execution fails. Apache receives a graceful restart signal after application is extracted in `/var/app/current` (after all running jobs failed).

What would be a good way to terminate runner? Stopping Supervisord? Should a new job be added in database "terminate runner" and when runner finishes all running jobs, then terminates? I guess that wouldn't work since supervisord will restart it again.

Any suggestions on this?

**Comment by nclavaud** [comment]
Maybe #83 could help? We are not using supervisord but a custom autorestart script which does the same job I guess.

Our deployment flow is as follow:
  * stop job runner autostart mechanism
  * let the job runner terminate (max runtime is a bit less than 5 minutes)
  * deploy
  * enable autostart again

**Comment by ggirtsou** [comment]
@nclavaud I'd really appreciate a sample of your deployment configuration that shows how you wait runner to terminate.

**Comment by nclavaud** [comment]
Our autostart script creates a lock file before starting the job runner and removes the lock file after the job runner has exited.

Something like:

```bash
#!/bin/bash

# run this script every minute in crontab

LOCK="test.lock"

function run {
    php console jms-job-queue:run -r 295
}

# if lock file exists, exit
[ -f "$LOCK" ] && echo "Job runner has already been started." && exit 0

# otherwise, create lock file, start the job runner, remove the lock file
touch $LOCK && echo "Starting job runner." && run && rm $LOCK
```

This bash script is run every minute by a cron to keep the job runner (almost) always up.

Before deploying, we comment the crontab to prevent the autostart, and we wait for the lock file to be removed. Then we know for sure that the job runner has finished processing the jobs, and we're free to deploy.

**Comment by ggirtsou** [comment]
Thanks, that helps a lot. But that means you have to wait until runner has finished. What if you want to deploy ASAP & there's a long running job? That kinda locks you out.
