### ISSUE TITLE
Configuration option to delete old jobs (optionally)

### ISSUE THREAD

**Issue by ggirtsou** [schmittjoh/JMSJobQueueBundle#91]
After a while, database size is considerably increased because of the output messages & stack traces stored in database.

Should an option be added to automatically delete old jobs? For instance keep history for up to 1 week.

If bundle won't handle this itself, a recurring command needs to be created by developers who use this bundle.

**Comment by nclavaud** [comment]
Looks like [jms-job-queue:clean-up](https://github.com/schmittjoh/JMSJobQueueBundle/blob/1.1.0/Command/CleanUpCommand.php) command does what you want.
